version: '3.8'
services:
  strapi:
    build:
      dockerfile: Dockerfile
      context: .
    image: main-strapi
    container_name: main-strapi
    env_file:
      - .env
    ports:
      - 1338:1337