name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Check Branch
        id: branch_check
        run: |
          if [[ "${{ github.base_ref }}" != "refs/heads/Dev" ]]; then
            echo "This push is not on the Dev branch."
            exit 0
          fi
      - name: Sync Dev to main
        if: steps.branch_check.outcome == 'success'
        run: | 
          git config pull.rebase false
          git pull origin Dev
          
      - name: Install Dependencies
        run: npm install
      - name: Build Production Code
        run: npm run build
      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          PROD_SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "public/"
          PROD_HOST: ${{ secrets.PROD_HOST }}
          PROD_USER: ${{ secrets.PROD_USER }}
          TARGET: ${{ secrets.PROD_TARGET }}
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
