name: Deploy to Production

on:
  push:
    branches:
      - Dev
  # pull_request:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Build and deploy
        run: |
          git checkout main
          git merge --ff-only Dev
      - name: Check for Conflicts
        run: git diff --quiet origin/Dev || { echo "There are conflicts in the code."; exit 1; }
      - name: Install Dependencies
        run: npm install
      - name: Build Production Code
        run: npm run build
      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          REMOTE_PATH: /var/www/html
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT