name: Deploy to Production

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
        env:
          NODE_VERSION: 16

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and deploy
        run: |
          git checkout main
          git merge --ff-only Dev

      - name: Check for Conflicts
        run: git diff --quiet origin/Dev || { echo "There are conflicts in the code."; exit 1; }

      - name: Install Dependencies
        run: npm install

      - name: Build Production Code
        run: npm run build

      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          REMOTE_PATH: /var/www/html
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
